import {
  LayoutDashboard, Clock, Timer, CalendarDays, Home, Package,
  Umbrella, Bell, CheckSquare, Video, FileText, ClipboardList,
  LogOut, Settings, MessageSquare, Workflow, BarChart2,
  Users, Building2, DollarSign, Gift, Briefcase, UserCheck,
  Compass,
} from 'lucide-react'

export const EMPLOYEE_NAV = [
  { label: 'Overview', path: '/employee/overview', icon: LayoutDashboard },
  { label: 'Attendance', path: '/employee/attendance', icon: Clock },
  { label: 'Overtime', path: '/employee/overtime', icon: Timer },
  { label: 'Leave', path: '/employee/leave', icon: CalendarDays },
  { label: 'Work From Home', path: '/employee/work-from-home', icon: Home },
  { label: 'Travel CRM', path: '/employee/crm', icon: Compass },
  { label: 'Chat', path: '/employee/chat', icon: MessageSquare },
  { label: 'Meeting Hub', path: '/employee/meeting-hub', icon: Video },
  { label: 'Notifications', path: '/employee/notifications', icon: Bell },
  { label: 'Assets', path: '/employee/assets', icon: Package },
  { label: 'Holidays', path: '/employee/holidays', icon: Umbrella },
  { label: 'Tasks', path: '/employee/tasks', icon: CheckSquare },
  { label: 'My Payslips', path: '/employee/payslips', icon: FileText },
  { label: 'Attendance Req', path: '/employee/attendance-request', icon: ClipboardList },
  { label: 'Resign', path: '/employee/resignation', icon: LogOut },
  { label: 'Settings', path: '/employee/settings', icon: Settings },
  { label: 'TaskFlow', path: '/employee/taskflow', icon: Workflow },
  { label: 'Reports', path: '/employee/reports', icon: BarChart2 },
]

export const ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin/dashboard', icon: LayoutDashboard },
  { label: 'Travel CRM', path: '/admin/crm', icon: Compass },
  { label: 'Company Chat', path: '/admin/chat', icon: MessageSquare },
  { label: 'Meeting Hub', path: '/admin/meeting-hub', icon: Video },
  { label: 'Notifications', path: '/admin/notifications', icon: Bell },
  { label: 'Users', path: '/admin/users', icon: UserCheck },
  { label: 'Employees', path: '/admin/employees', icon: Users },
  { label: 'Departments', path: '/admin/departments', icon: Building2 },
  { label: 'Designations', path: '/admin/designations', icon: Briefcase },
  { label: 'Attendance', path: '/admin/attendance', icon: Clock },
  { label: 'Attendance Req', path: '/admin/attendance-requests', icon: ClipboardList },
  { label: 'Overtime', path: '/admin/overtime', icon: Timer },
  { label: 'Work From Home', path: '/admin/work-from-home', icon: Home },
  { label: 'Leave Management', path: '/admin/leave-management', icon: CalendarDays },
  { label: 'Payroll', path: '/admin/payroll', icon: DollarSign },
  { label: 'Assets', path: '/admin/assets', icon: Package },
  { label: 'Holidays', path: '/admin/holidays', icon: Gift },
  { label: 'Resignations', path: '/admin/resignation', icon: LogOut },
  { label: 'Reports', path: '/admin/reports', icon: BarChart2 },
  { label: 'Settings', path: '/admin/settings', icon: Settings },
]
